### ISSUE TITLE
Spelling Mistake In Localisation?

### ISSUE THREAD

**Issue by edent** [twitterdev/TwitterKitSample#1]
A few instances of "Twiter" appear to have crept in to the Indonesian localisation.

https://github.com/twitterdev/FabricWithTwitter/blob/master/iOS/WatchSample/TwitterKit.framework/Versions/A/Resources/TwitterKitResources.bundle/DigitsResources.bundle/ms.lproj/Localizable.strings

**Comment by andypiper** [comment]
Removed the watch sample in the new version as it was not using Twitter Kit.
