### ISSUE TITLE
Found a typo with `TWTRLoginErrorNoTwitterApp`

### ISSUE THREAD

**Issue by dacchan** [twitterdev/TwitterKitSample#10]
Hi.

I think that it is `TWTRLogInErrorNoTwitterApp` properly.

See: https://github.com/twitterdev/TwitterKitSample/blob/436c18b475444364993bc74ff189231944a70666/iOS/TableViewTweetsSwift/TableViewTweetsSwift/TwitterCore.framework/Headers/TWTRConstants.h#L143

**Comment by andypiper** [comment]
archiving repo due to Twitter Kit deprecation
