### ISSUE TITLE
Error in Android Studio 1.3.1 used unsupporter version android gradle plug in (0.13.2)

### ISSUE THREAD

**Issue by gabrielacosta** [twitterdev/TwitterKitSample#5]
Hi Ryan, 

I downloaded the last version of FabricWithTwitter and I was trying to check the Android example projects (DisplayTweets and WearExample) . When I import the DisplayTweets Project Android Studio 1.3.1 show me the error:

> used unsupported version android gradle plug in (0.13.2). Use gradle:1.3.0

I accept the fixed using the classpath 'com.android.tools.build:gradle:1.3.0' instead of the 0.13.2 as recommended by the IDE.

Also change the runProguard() for minifyEnabled
Modify the Project Settings to use Gradle version 2.2.1, for fixed this error :

> Error:(31, 0) Gradle DSL method not found: 'runProguard()'

After that, the gradle plugin works. However, a new error occurs when building the app:

Error:Execution failed for task ':app:fabricGenerateResourcesDebug'.

> Crashlytics Developer Tools error.

Look the current log:

> Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources]
> :app:preBuild UP-TO-DATE
> :app:preDebugBuild UP-TO-DATE
> :app:checkDebugManifest
> :app:preReleaseBuild UP-TO-DATE
> :app:prepareComAndroidSupportSupportV42100Library
> :app:prepareComDigitsSdkAndroidDigits102Library
> :app:prepareComTwitterSdkAndroidTweetComposer072Library
> :app:prepareComTwitterSdkAndroidTweetUi102Library
> :app:prepareComTwitterSdkAndroidTwitter110Library
> :app:prepareComTwitterSdkAndroidTwitterCore110Library
> :app:prepareIoFabricSdkAndroidFabric102Library
> :app:prepareDebugDependencies
> :app:compileDebugAidl
> :app:compileDebugRenderscript
> :app:generateDebugBuildConfig
> :app:generateDebugAssets UP-TO-DATE
> :app:mergeDebugAssets
> :app:generateDebugResValues
> :app:generateDebugResources
> :app:mergeDebugResources
> :app:processDebugManifest
> :app:fabricGenerateResourcesDebug
> ERROR - Crashlytics Developer Tools error.
> java.lang.IllegalArgumentException: Crashlytics found an invalid API key: . 
> Check the Crashlytics plugin to make sure that the application has been added successfully! 
> Contact support@fabric.io for assistance.
>     at com.crashlytics.tools.android.DeveloperTools.processApiKey(DeveloperTools.java:326)
>     at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:466)
>     at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:299)
>     at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:270)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:601)
>     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
>     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
>     at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43)
>     at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
>     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
>     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
>     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
>     at com.crashlytics.tools.gradle.tasks.FabricTaskBuilder.callDevtoolsWrappingRuntimeExceptions(FabricTaskBuilder.groovy:313)
>     at com.crashlytics.tools.gradle.tasks.FabricTaskBuilder.this$2$callDevtoolsWrappingRuntimeExceptions(FabricTaskBuilder.groovy)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:601)
>     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
>     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
>     at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:368)
>     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
>     at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
>     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
>     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
>     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
>     at com.crashlytics.tools.gradle.tasks.FabricTaskBuilder$_pluginGenerateResources_closure3.doCall(FabricTaskBuilder.groovy:112)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:601)
>     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
>     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
>     at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
>     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
>     at groovy.lang.Closure.call(Closure.java:423)
>     at groovy.lang.Closure.call(Closure.java:439)
>     at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:548)
>     at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:529)
>     at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
>     at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
>     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
>     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
>     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
>     at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>     at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
>     at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
>     at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
>     at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>     at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
>     at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>     at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
>     at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
>     at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
>     at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
>     at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
>     at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
>     at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
>     at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
>     at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
>     at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
>     at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
>     at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
>     at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
>     at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
>     at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
>     at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
>     at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
>     at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:43)
>     at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:30)
>     at org.gradle.tooling.internal.provider.ConfiguringBuildAction.run(ConfiguringBuildAction.java:119)
>     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
>     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
>     at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
>     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
>     at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
>     at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
>     at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
>     at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
>     at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
>     at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
>     at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
>     at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
>     at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
>     at org.gradle.util.Swapper.swap(Swapper.java:38)
>     at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
>     at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
>     at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
>     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
>     at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
>     at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
>     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
>     at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
>     at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
>     at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
>     at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
>     at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
>     at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
>     at java.lang.Thread.run(Thread.java:722)
> :app:fabricGenerateResourcesDebug FAILED
> Error:Execution failed for task ':app:fabricGenerateResourcesDebug'.
> Crashlytics Developer Tools error.

Update: WearExample show me the same error.

Could you give a hand checking this and suggesting me how to fixed the issue.

Kind regards, 

Juan

**Comment by andypiper** [comment]
archiving repo due to Twitter Kit deprecation
