### ISSUE TITLE
loginGuest parameter mistake?

### ISSUE THREAD

**Issue by emirBytes** [twitterdev/TwitterKitSample#7]
There is error for this line

` Twitter.sharedInstance().logInGuest { (session: TWTRGuestSession!, error: NSError!) in`

/Users/Emir/Downloads/FabricWithTwitter-master/iOS/TableViewTweetsSwift/TableViewTweetsSwift/ViewController.swift:66:45: Cannot convert value of type '(TWTRGuestSession!, NSError!) -> Void' to expected argument type 'TWTRGuestLogInCompletion!'

**Comment by andypiper** [comment]
Resolved in the update to Twitter Kit 3. Thanks.
